//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicielAdaptatif.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id_product { get; set; }
        public string product_name { get; set; }
        public int product_stock { get; set; }
        public string product_picture { get; set; }
        public string product_price { get; set; }
    }
}
